spring:
  profiles:
    active: dev
  application:
    name: limit-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
server:
  port: 8080

limit-service:
  min: 2
  max: 98